version: '3.1'

services:
  web:
    build: .
    ports:
      - "3000:3000"

  prometheus:
    build:
      context: .
      dockerfile: docker-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
